codecov:
  branch: dev
  require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "0...100" # This ensures that Codecov never fails the CI build

  status:
    project:
      default:
        target: 0% # This ensures that codecov/project will never fail the CI build
    patch:
      default:
        target: 0% # This ensures that codecov/patch will never fail the CI build

comment:
  behavior: default
  layout: "diff, flags, files"
  require_base: no
  require_head: no
  show_carryforward_flags: true

flags:
  pg_bm25:
    paths:
      - pg_bm25/*
    carryforward: true
  pg_columnar:
    paths:
      - pg_columnar/*
    carryforward: true
  pg_sparse:
    paths:
      - pg_sparse/*
    carryforward: true
  shared:
    paths:
      - shared/*
    carryforward: true
