[workspace]
resolver = "2"
members = ["cargo-paradedb", "pg_search", "tests", "tokenizers"]

[workspace.package]
version = "0.13.2"
edition = "2021"
license = "AGPL-3.0"

[profile.dev]
panic = "unwind"

[profile.release]
lto = "fat"
panic = "unwind"
opt-level = 3
codegen-units = 1

[profile.prof]
inherits = "release"
debug = true
lto = "thin"
codegen-units = 32

[workspace.dependencies]
#tantivy = { git = "https://github.com/paradedb/tantivy.git", package = "tantivy", rev = "e22ad2b9f2f8ce8fc1dfe197c7e980b53f73e735", features = [
#  "quickwit",        # for sstable support
#  "stopwords",
#  "lz4-compression",
#], default-features = false }
#tantivy-common = { git = "https://github.com/paradedb/tantivy.git", rev = "e22ad2b9f2f8ce8fc1dfe197c7e980b53f73e735" }

tantivy = { path = "/home/zombodb/_work/tantivy", features = [
  "quickwit",        # for sstable support
  "stopwords",
  "lz4-compression",
], default-features = false }
tantivy-common = { path = "/home/zombodb/_work/tantivy/common" }
