[workspace]
resolver = "2"
members = [
    "pg_bm25",
<<<<<<< HEAD
=======
    "pg_columnar",
>>>>>>> 08b51c26 (feat: Basic clickbench in pgrx (#5))
    "shared"
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
