[workspace]
resolver = "2"
members = [
    "pg_analytics",
    "pg_search",
    "shared",
    "tokenizers",
]

[profile.dev]
panic = "unwind"

[profile.release]
lto = "fat"
panic = "unwind"
opt-level = 3
codegen-units = 1
