[workspace]
resolver = "2"
members = [
    "pg_bm25",
    "pg_columnar",
    "shared"
]

[profile.dev]
panic = "unwind"

[profile.release]
lto = "fat"
panic = "unwind"
opt-level = 3
codegen-units = 1
