[workspace]
resolver = "2"
members = ["cargo-paradedb", "pg_search", "tests", "tokenizers"]

[workspace.package]
version = "0.14.0"
edition = "2021"
license = "AGPL-3.0"

[profile.dev]
panic = "unwind"

[profile.release]
lto = "fat"
panic = "unwind"
opt-level = 3
codegen-units = 1

[profile.prof]
inherits = "release"
debug = true
lto = "thin"
codegen-units = 32

[workspace.dependencies]
tantivy = { git = "https://github.com/paradedb/tantivy.git", package = "tantivy", rev = "cc0f329a1df02c21085d520a07f92665cbe4ceee", features = [
  "quickwit",        # for sstable support
  "stopwords",
  "lz4-compression",
], default-features = false }
tantivy-common = { git = "https://github.com/paradedb/tantivy.git", rev = "cc0f329a1df02c21085d520a07f92665cbe4ceee" }
