[workspace]
resolver = "2"
members = [
    "pg_bm25",
    "pg_search",
    "pg_sparse",
    "shared"
]

# This profile is optimized for the shortest possible compile times
# and is meant for our CI pipelines exclusively.
[profile.ci]
inherits = "dev"
opt-level = 1
lto = false
codegen-units = 16
debug = false

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
