[workspace]
resolver = "2"
members = [
    "pg_bm25",
<<<<<<< HEAD
=======
    "pg_columnar",
    "pg_search",
    "pg_sparse",
>>>>>>> 209bbf1b (begin implementing table AM)
    "shared"
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1
