# This docker-compose.dev.yml file is for local development only.

version: "3"

services:
  core:
    extends:
      file: ./docker-compose.yml
      service: core

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - core
    ports:
      - 8000:8000
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      API_KEY: retake-test-key
      OPENSEARCH_HOST: core
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: admin
      OPENSEARCH_USE_TLS: False
      PGSYNC_HOST: pgsync
      PGSYNC_PORT: 7433
      PGSYNC_SSL_ENABLED: False
    volumes:
      - .:/app

  redis:
    extends:
      file: ./docker-compose.yml
      service: redis
    
  pgsync:
    extends:
      file: ./docker-compose.yml
      service: pgsync
