version: "3"

services:
  core:
    image: public.ecr.aws/opensearchproject/opensearch:latest
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=false
      - plugins.ml_commons.model_access_control_enabled=true
      - plugins.ml_commons.only_run_on_ml_node=false

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - API_KEY=retake-test-key
