version: "3.9"

services:
  deps:
    image: python:3.9-slim
    volumes:
      - .:/app
      - python-deps:/usr/local/lib/python3.9/site-packages
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        apt-get update &&
        apt-get install -y curl &&
        curl -sSL https://install.python-poetry.org | python - &&
        export PATH="/root/.local/bin:$PATH" &&
        poetry config virtualenvs.create false &&
        poetry install

  cdc:
    image: python:3.9-slim
    volumes:
      - .:/app
      - python-deps:/usr/local/lib/python3.9/site-packages
    working_dir: /app
    entrypoint:
      - python
      - -m
      - cdc.run

volumes:
  python-deps:
