title: "[Ideas] "
labels: ["feature", "idea", "suggestion"]
body:
  - type: markdown
    attributes:
      value: >
        Please report security vulnerabilities using GitHub's [report vulnerability form](https://github.com/paradedb/paradedb/security/advisories/new).

  - type: textarea
    attributes:
      label: What idea are you proposing?
      description: A short, clear and concise description of the desired feature or proposed idea.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why are you proposing this idea?
      description: A short, clear and concise description of why this feature or idea is important.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Identity Disclosure:"
  - type: input
    attributes:
      label: "Full Name:"
      placeholder: e.g., John Doe
    validations:
      required: true
  - type: input
    attributes:
      label: "Affiliation:"
      placeholder: e.g., Acme Corporation
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.
