[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

# Run ClickBench benchmarks via `cargo clickbench`
[alias]
clickbench = "run --bin clickbench"
