#
# This docker-compose.dev.yml file is for development of the Parade DBMS only. It builds our
# Dockerfile, which is the full ParadeDB image with all extensions, and all other ParadeDB services,
# to allow for complete testing of the ParadeDB system. It is not intended for production use.
#

version: "3.8"

services:
  paradedb:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        PG_VERSION_MAJOR: 15
        PG_BM25_VERSION: 0.0.0
        PG_SEARCH_VERSION: 0.0.0
        PGVECTOR_VERSION: 0.5.1
        PGNODEMX_VERSION: 1.6
        PG_CRON_VERSION: 1.6.0
        PG_NET_VERSION: 0.7.2
        PG_IVM_VERSION: 1.5.1
        PG_GRAPHQL_VERSION: 1.3.0
        PG_HASHIDS_VERSION: 1.2.1
        PG_JSONSCHEMA_VERSION: 0.1.4
        PG_REPACK_VERSION: 1.4.8
        PG_STAT_MONITOR_VERSION: 2.0.1
        PG_HINT_PLAN_VERSION: 1.5.0
        PG_ROARINGBITMAP_VERSION: 0.5.4
        PGFACETING_VERSION: 0.1.0
        PGTAP_VERSION: 1.3.0
        PGAUDIT_VERSION: 1.7.0
        POSTGIS_VERSION: 3.4.0
        PGROUTING_VERSION: 3.5.0
        PGSQL_HTTP_VERSION: 1.6.0
        HYPOPG_VERSION: 1.4.0
        RUM_VERSION: 1.3.13
        AGE_VERSION: 1.4.0
      cache_from:
        - type=local,src=./.docker_cache_dev
      cache_to:
        - type=local,dest=./.docker_cache_dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
