#
# This docker-compose.dev.yml file is for development of the Parade DBMS only. It builds our
# Dockerfile, which is the full ParadeDB image with all extensions, and all other ParadeDB services,
# to allow for complete testing of the ParadeDB system. It is not intended for production use.
#

version: "3.8"

services:
  paradedb-dev:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        PG_VERSION_MAJOR: 15
        PG_BM25_VERSION: 0.0.0
        PG_ANALYTICS_VERSION: 0.0.0
        PG_SPARSE_VERSION: 0.0.0
      cache_from:
        - type=local,src=./.docker_cache_dev
      cache_to:
        - type=local,dest=./.docker_cache_dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - paradedb-data:/var/lib/postgresql/data

volumes:
  paradedb-data:
