#
# This docker-compose.yml file is for production deployments of ParadeDB. It pulls the latest
# ParadeDB image from Docker Hub, which has all ParadeDB extensions pre-installed and properly configured.
# It is intended for hobby production use. Make sure to update POSTGRES_USER, POSTGRES_PASSWORD, and
# POSTGRES_DB before production usage.
#

services:
  paradedb:
    image: paradedb/paradedb:latest
    container_name: paradedb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PARADEDB_TELEMETRY: true # Set to 'false' (or remove) to disable anonymous telemetry
    ports:
      - "5432:5432"
    volumes:
      - paradedb_data:/var/lib/postgresql

volumes:
  paradedb_data:
