# This docker-compose.yml file is for a hobby production deploy.

version: "3.8"

services:
  core:
    extends:
      file: ./docker-compose.base.yml
      service: core

  api:
    extends:
      file: ./docker-compose.base.yml
      service: api
    environment:
      API_KEY: retake-test-key
      POSTHOG_API_KEY: phc_KiWfPSoxQLmFxY5yOODDBzzP3EcyPbn9oSVtsCBbasj
      OPENSEARCH_HOST: core
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: admin
      OPENSEARCH_VERIFY_CERTS: False
      PGSYNC_HOST: pgsync
      PGSYNC_PORT: 7433


  redis:
    extends:
      file: ./docker-compose.base.yml
      service: redis

  pgsync:
    extends:
      file: ./docker-compose.base.yml
      service: pgsync

  caddy:
    image: caddy:2.7.2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ../Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
