#
# This docker-compose.yml file is for production deployments of ParadeDB. It pulls the latest
# ParadeDB image from Docker Hub, which has all extensions pre-installed. It is intended for hobby
# production use. Make sure to change the POSTGRES_USER, POSTGRES_PASSWORD, and POSTGRES_DB to appropriate values.
#

version: "3.8"

services:
  paradedb:
    image: paradedb/paradedb:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRESQL_SHARED_PRELOAD_LIBRARIES: pgaudit,pg_bm25,pg_analytics
      TELEMETRY: true # Set this variable to 'false' (or remove it) to disable anonymous telemetry
    ports:
      - "5432:5432"
    volumes:
      - paradedb-data:/var/lib/postgresql/data

volumes:
  paradedb-data:
