#
# This docker-compose.dev.yml file is for development of the Parade DBMS only. It builds our
# Dockerfile, which is the full ParadeDB image with all extensions, to allow for complete
# testing of the ParadeDB system. It is not intended for production use.
#

version: "3.8"

services:
  paradedb-dev:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      cache_from:
        - type=local,src=./.docker_cache_dev
      cache_to:
        - type=local,dest=./.docker_cache_dev
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRESQL_POSTGRES_PASSWORD: postgres # Password for the superuser (optional)

      # POSTGRESQL_USERNAME: myuser
      # POSTGRESQL_PASSWORD: mypassword
      # POSTGRESQL_DATABASE: mydatabase
      # POSTGRESQL_SHARED_PRELOAD_LIBRARIES: pgaudit,pg_bm25,pg_analytics
    ports:
      - "5432:5432"
    # volumes:
    #   - paradedb-data:/var/lib/postgresql/data
# volumes:
#   paradedb-data:
