# PostgreSQL symbols won't be available until runtime
[target.'cfg(target_os="macos")']
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

# Enable code coverage on Linux only, for CI builds
[target.'cfg(target_os="linux")']
rustflags = ["-Cinstrument-coverage"]

# Global settings - optimize for the native CPU for all targets. This
# is required by the 'datafusion` crate for maximum performance
[build]
rustflags = ["-Ctarget-cpu=native"]

# Enable Cargo-based benchmarks
[alias]
clickbench = "run --bin clickbench --"
