# PostgreSQL symbols won't be available until runtime
[target.'cfg(target_os="macos")']
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

# Enable code coverage on Linux only, for CI builds
[target.'cfg(target_os="linux")']
rustflags = ["-Cinstrument-coverage"]

# Run ClickBench benchmarks
[alias]
clickbench = "run --bin clickbench_hot"
clickbench_cold = "run --bin clickbench_cold"
