# PostgreSQL symbols won't be available until runtime
[target.'cfg(target_os="macos")']
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

# Enable code coverage on Linux only, for CI builds
[target.'cfg(target_os="linux")']
rustflags = ["-Cinstrument-coverage", "-Z", "threads=8"]
