[package]
name = "pg_search"
description = "Full text search for PostgreSQL using BM25"
version = "0.9.4"
edition = "2021"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["pg16"]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16"]
pg_test = []
icu = ["tokenizers/icu"]

[dependencies]
anyhow = { version = "1.0.87", features = ["backtrace"] }
bincode = "1.3.3"
crossbeam = "0.8.4"
csv = "1.3.0"
derive_more = "0.99.18"
fs2 = "0.4.3"
indexmap = "2.5.0"
interprocess = "1.2.1"
json5 = "0.4.1"
libc = "0.2.158"
memoffset = "0.9.1"
once_cell = "1.19.0"
tokenizers = { version = "0.9.4", path = "../tokenizers" }
pgrx = "0.12.3"
reqwest = "0.11.27"
rustc-hash = "1.1.0"
serde = "1.0.210"
serde_json = "1.0.128"
serde_path_to_error = "0.1.16"
shared = { path = "../shared" }
tantivy = { git = "https://github.com/paradedb/tantivy.git", package = "tantivy", rev = "33be46c" }
tantivy-common = { git = "https://github.com/paradedb/tantivy.git", rev = "33be46c" }
thiserror = "1.0.63"
tiny_http = "0.12.0"
tracing = "0.1.40"
utoipa = "4.2.3"
walkdir = "2.5.0"
num_cpus = "1.16.0"
chrono = "0.4.38"
ordered-float = "4.2.2"
uuid = "1.10.0"
strum = { version = "0.26.3" }

[dev-dependencies]
approx = "0.5.1"
async-std = { version = "1.13.0", features = ["attributes"] }
cmd_lib = "1.9.4"
dotenvy = "0.15.7"
pgrx-tests = "0.12.3"
pgvector = { version = "0.3.4", features = ["sqlx"] }
portpicker = "0.1.1"
pretty_assertions = "1.4.0"
rstest = "0.18.2"
shared = { path = "../shared", features = ["fixtures"] }
sqlx = { version = "0.7.4", features = [
  "postgres",
  "runtime-async-std",
  "time",
  "bigdecimal",
  "uuid",
] }
tempfile = "3.12.0"

[package.metadata.cargo-machete]
ignored = ["indexmap", "libc", "tantivy-common"]

[[bin]]
name = "pgrx_embed_pg_search"
path = "./src/bin/pgrx_embed.rs"
