[package]
name = "pg_search"
description = "Full text search for PostgreSQL using BM25"
version = "0.9.1"
edition = "2021"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["pg16"]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16"]
pg_test = []
icu = ["tokenizers/icu"]

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
bincode = "1.3.3"
csv = "1.2.2"
derive_more = "0.99.17"
fs2 = "0.4.3"
indexmap = "2.1.0"
interprocess = "1.2.1"
json5 = "0.4.1"
libc = "0.2.152"
memoffset = "0.9.0"
once_cell = "1.18.0"
tokenizers = { version = "0.9.1", path = "../tokenizers" }
pgrx = { git = "https://github.com/paradedb/pgrx.git", rev = "2737a13" }
reqwest = "0.11.22"
rustc-hash = "1.1.0"
serde = "1.0.188"
serde_json = "1.0.105"
serde_path_to_error = "0.1.14"
shared = { path = "../shared" }
tantivy = { git = "https://github.com/paradedb/tantivy.git", package = "tantivy", rev = "c7f13ef" }
tantivy-common = { git = "https://github.com/paradedb/tantivy.git", rev = "c7f13ef" }
thiserror = "1.0.56"
tiny_http = "0.12.0"
tracing = "0.1.40"
utoipa = "4.2.0"
walkdir = "2.5.0"
num_cpus = "1.16.0"
chrono = "0.4.38"
ordered-float = "4.2.0"
uuid = "1.10.0"

[dev-dependencies]
approx = "0.5.1"
async-std = { version = "1.12.0", features = ["attributes"] }
cmd_lib = "1.9.4"
dotenvy = "0.15.7"
pgrx-tests = { git = "https://github.com/paradedb/pgrx.git", rev = "2737a13" }
pgvector = { version = "0.3.2", features = ["sqlx"] }
portpicker = "0.1.1"
pretty_assertions = "1.4.0"
rstest = "0.18.2"
shared = { path = "../shared", features = ["fixtures"] }
sqlx = { version = "0.7.3", features = [
  "postgres",
  "runtime-async-std",
  "time",
  "bigdecimal",
  "uuid",
] }
tempfile = "3.9.0"

[package.metadata.cargo-machete]
ignored = ["indexmap", "libc", "tantivy-common"]
