[package]
name = "pg_search"
description = "Hybrid search for PostgreSQL"
version = "0.0.0"
edition = "2021"
license = "Elastic License 2.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg15"]
pg11 = ["pgrx/pg11", "pgrx-tests/pg11" ]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12" ]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13" ]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14" ]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15" ]
pg_test = []

[dependencies]
pgrx = "=0.9.8"
posthog-rs = "0.2.2"
serde = "1.0.188"
uuid = "1.4.1"

[dev-dependencies]
pgrx-tests = "=0.9.8"
