[package]
name = "shared"
description = "Shared code for ParadeDB crates"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[features]
default = ["pg16"]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16"]
pg_test = []
telemetry = []
fixtures = ["async-std", "rstest", "soa_derive", "sqlx", "bigdecimal"]

[dependencies]
envy = "0.4.2"
pgrx = "0.11.2"
reqwest = { version = "0.11.22", features = ["blocking"] }
serde = "1.0.189"
serde_json = "1.0.107"
time = { version = "0.3.34", features = ["serde"] }
tracing = "0.1.40"
uuid = "1.5.0"
async-std = { version = "1.12.0", features = ["attributes"], optional = true }
rstest = { version = "0.18.2", optional = true }
soa_derive = { version = "0.13.0", optional = true }
sqlx = { version = "0.7.3", features = [
  "postgres",
  "runtime-async-std",
  "time",
  "bigdecimal",
  "uuid",
], optional = true }
bigdecimal = { version = "0.3.0", features = ["serde"], optional = true}
bytes = "1.5.0"
thiserror = "1.0.57"
once_cell = "1.19.0"
url = "2.5.0"
derive_builder = "0.20.0"
walkdir = "2.5.0"

[dev-dependencies]
mockall = "0.12.1"
pgrx-tests = "0.11.2"
tempfile = "3.10.1"
