[package]
name = "shared"
description = "Shared code for ParadeDB crates"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[features]
telemetry = []

[dependencies]
envy = "0.4.2"
pgrx = "0.11.2"
reqwest = { version = "0.11.22", features = ["blocking"] }
serde = "1.0.189"
serde_json = "1.0.107"
uuid = "1.5.0"

[dev-dependencies]
pgrx-tests = "0.11.2"
