# workflows/benchmark-pg_analytics.yml
#
# Benchmark pg_analytics
# Benchmark ParadeDB's pg_analytics performance on a nightly basis. This workflow can also be triggered
# manually to benchmark other systems on one-off basis, to compare against ParadeDB.

name: Benchmark pg_analytics

on:
  schedule:
    - cron: "1 0 * * 1,2,3,4,5" # Run once per day on weekdays (days of the week 1-5) at 00:01 UTC
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "docker/Dockerfile"
      - "pg_analytics/Cargo.toml"
      - "pg_analytics/benchmarks/**"
      - ".github/workflows/benchmark-pg_analytics.yml"
  workflow_dispatch:

concurrency:
  group: benchmark-pg_analytics-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark-pg_analytics:
    name: Benchmark pg_analytics on ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - name: ClickBench
            runner: ubuntu-latest-m # Size: 4-cores · 16 GB RAM · 150 GB SSD
            path: clickbench/
            flags: ""
          - name: TPC-H (OLAP)
            runner: ubuntu-latest-m # Size: 4-cores · 16 GB RAM · 150 GB SSD
            path: tpch/
            flags: -w olap
          - name: TPC-H (HTAP)
            runner: ubuntu-latest-m # Size: 4-cores · 16 GB RAM · 150 GB SSD
            path: tpch/
            flags: -w htap

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      # Set the MACHINE variable to LINUX for TPC-H benchmarks, since
      # the default is MACOS for development
      - name: Update TPC-H Data Generation Makefile
        if: ${{ matrix.name == 'TPC-H (OLAP)' || matrix.name == 'TPC-H (HTAP)' }}
        working-directory: pg_analytics/benchmarks/tpch/TPC-H_V3.0.1/dbgen/
        run: sed -i 's/MACHINE = .*/MACHINE = LINUX/' makefile

      - name: Run Official ${{ matrix.name }} Benchmark
        working-directory: pg_analytics/benchmarks/${{ matrix.path }}
        run: ./benchmark.sh -t local ${{ matrix.flags }}

      - name: Notify Slack on Failure
        if: failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Benchmark pg_analytics Workflow failed on ${{ steps.system.outputs.system_to_benchmark }} -- investigate immediately!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
