# workflows/lint-python.yml
#
# Lint Python
# Lint Python files using Black, Pylint, and Flake8.

name: Lint Python

on:
  pull_request:
    paths:
      - "**/*.sh"
      - ".github/workflows/lint-bash.yml"
  workflow_dispatch:

concurrency:
  group: lint-python-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install black pylint flake8

      - name: Run Black for Code Formatting
        run: black --check .

      - name: Run Pylint for Static Code Analysis
        run: pylint **/*.py

      - name: Run Flake8 for Style Guide Enforcement
        run: flake8 . --max-line-length=100
