# workflows/lint-python.yml
#
# Python: Linting
# Lint Python code using Black, Flake8 & Mypy.

name: "Lint Python and check types"

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: lint-python-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v3

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Run Black
        run: poetry run black --check .

      - name: Run Flake8
        run: poetry run flake8 core retake streams connectors

      - name: Run Mypy
        run: poetry run mypy core retake streams connectors
