# workflows/lint-python.yml
#
# Lint Python
# Lint Python files using Black, Pylint, and Flake8.

name: Lint Python

on:
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/lint-python.yml"
  workflow_dispatch:

concurrency:
  group: lint-python-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-python:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Ruff for Linting and Formatting
        uses: chartboost/ruff-action@v1

      - name: Run Pylint for Static Code Analysis
        run: pip install pylint ** pylint **/*.py
