# workflows/lint-typescript.yml
#
# TypeScript: Linting
# Lint TypeScript files using Prettier.

name: Linting

on:
  pull_request:
    paths:
      - "**/**.js"
      - "**/**.ts"
      - "**/**.tsx"
      - "**/**.css"
      - "**/**.json"
      - ".github/workflows/lint-typescript.yml"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: lint-typescript-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-typescript:
    name: Lint TypeScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v3

      - name: root
        run: npm root -g

      - name: Install ESLint & ESLint Plugins
        run: |
          npm install -g prettier \
                         eslint \
                         @typescript-eslint/eslint-plugin \
                         eslint-config-next \
                         eslint-config-prettier \
                         eslint-config-standard \
                         eslint-plugin-unused-imports \

                         npm install @typescript-eslint/eslint-plugin@latest --save-dev

                         npm install -g @typescript-eslint/eslint-plugin @typescript-eslint/parser




      - name: Check if TypeScript Files are ESLint Formatted
        run: eslint '{**/**.js,**/**.ts,**/**.tsx,**/**.css,**/**.json}'

      - name: Check if TypeScript Files are Prettier Formatted
        run: prettier --check '{**/**.js,**/**.ts,**/**.tsx,**/**.css,**/**.json}'
