# workflows/lint-typescript.yml
#
# Lint TypeScript
# Lint TypeScript and related files (i.e. .json, .css, etc.) using ESLint and Prettier.

name: Lint TypeScript

on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.json"
      - ".github/workflows/lint-typescript.yml"
  workflow_dispatch:

concurrency:
  group: lint-typescript-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-typescript:
    name: Lint TypeScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: dashboard/
        run: npm install

      - name: Run ESLint
        run: npx eslint "**/*.js" "**/*.ts" "**/*.tsx"

      - name: Run Prettier Check
        run: npx prettier --check "**/*.js" "**/*.ts" "**/*.tsx" "**/*.css" "**/*.json"
