# workflows/lint-pre-commit.yml
#
# Lint Pre-Commit
# Lint the entire repository using pre-commit hooks.

name: Lint Pre-Commit

on:
  pull_request:
    branches:
      - main
      - staging
      - dev
  workflow_dispatch:

concurrency:
  group: lint-pre-commit-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update && sudo apt-get install -y postgresql-15 postgresql-server-dev-15

      - name: Install pgrx
        run: cargo install --locked cargo-pgrx --version 0.11.0

      - name: Initialize pgrx for Current PostgreSQL Version
        run: cargo pgrx init --pg15=/usr/lib/postgresql/15/bin/pg_config

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: |
          export SKIP=detect-aws-credentials
          pre-commit run --all-files
