# workflows/lint-rust.yml
#
# Lint Rust
# Lint Rust files using Clippy and Rustfmt.

# name: Lint Rust

# on:
#   pull_request:
#     paths:
#       - "**/*.rs"
#       - ".github/workflows/lint-rust.yml"
#   workflow_dispatch:

# concurrency:
#   group: lint-rust-${{ github.head_ref || github.ref }}
#   cancel-in-progress: true

# jobs:
#   lint-rust:
#     name: Lint Rust Files
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Git Repository
#         uses: actions/checkout@v4

#       - name: Setup Rust
#         uses: actions-rust-lang/setup-rust-toolchain@v1
#         with:
#           components: clippy,rustfmt
#           cache: false # We cache the dependencies ourselves

#       - name: Install & Configure Supported PostgreSQL Version
#         run: |
#           wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
#           sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
#           sudo apt-get update && sudo apt-get install -y postgresql-15 postgresql-server-dev-15

#       - name: Install pgrx
#         run: cargo install --locked cargo-pgrx --version 0.11.1

#       - name: Initialize pgrx for Current PostgreSQL Version
#         run: cargo pgrx init --pg15=/usr/lib/postgresql/15/bin/pg_config

#       - name: Run Rustfmt
#         run: find . -name "*.rs" | xargs rustfmt --check

#       - name: Run Clippy
#         run: cargo clippy --workspace --all-targets -- -D warnings
