# workflows/lint-yaml.yml
#
# YAML: Linting
# Lint YAML files using Prettier.

name: Linting

on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    name: Lint YAML Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v3

      - name: Install Prettier
        run: npm install -g prettier

      - name: Check YAML Formatting
        run: prettier --check "**/*.{yml,yaml}"
