# workflows/publish-third-party-pg_extensions.yml
#
# Third-Party PostgreSQL Extensions: Publish
# Build and publish the third-party PostgreSQL extensions used by ParadeDB to
# GitHub Releases. We use a separate storage repo, paradedb/third-party-pg_extensions)
# for clarity and to avoid bloating the ParadeDB repo with binaries.

name: Publishing

on:
  push:
    branches:
      - main
    paths:
      - "conf/third_party_pg_extensions.json"
      - ".github/workflows/publish-third-party-pg_extensions.yml"
  workflow_dispatch:

concurrency:
  group: publish-third-party-pg_extensions-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-third-party-pg_extensions:
    name: Publish Third-Party PostgreSQL Extensions for PostgreSQL ${{ matrix.pg_version }} on ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            pg_version: 15
            arch: amd64
          - runner: buildjet-4vcpu-ubuntu-2204-arm
            pg_version: 15
            arch: arm64

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Retrieve GitHub Tag Version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
          sudo apt-get update && sudo apt-get install -y --no-install-recommends postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}

          # Update permissions for PostgreSQL directories for extensions installation
          sudo chown -R $(whoami) \
            /usr/share/postgresql/${{ matrix.pg_version }}/extension/ \
            /usr/lib/postgresql/${{ matrix.pg_version }}/bin/ \
            /usr/lib/postgresql/${{ matrix.pg_version }}/lib/ \
            /usr/include/postgresql/${{ matrix.pg_version }}/server/ \
            /usr/share/postgresql/${{ matrix.pg_version }}/contrib/ \
            /usr/local/share/man/ \
            /usr/share/doc/

          # Add PostgreSQL binaries to PATH
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      # Install requirements for: rum, pgaudit, postgis, pg_repack, AGE
      - name: Install Third-Party PostgreSQL Extension Build Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            checkinstall \
            systemtap-sdt-dev \
            libkrb5-dev \
            libgeos-dev \
            libproj-dev \
            libprotobuf-c-dev \
            libsfcgal-dev \
            libxml2-dev \
            libjson-c-dev \
            libgdal-dev \
            gdal-bin \
            gettext \
            libtool \
            xsltproc \
            protobuf-c-compiler \
            zlib1g-dev \
            bison \
            flex \
            libreadline-dev

      # We release third-party PostgreSQL extensions to a dedicated repository (paradedb/third-party-pg_extensions)
      - name: Build and Push Third-Party PostgreSQL Extensions to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
          PG_MAJOR_VERSION: ${{ matrix.pg_version }}
          ARCH: ${{ matrix.arch }}
        run: |
          extensions=$(jq -r '.extensions | keys[]' conf/third_party_pg_extensions.json)
          for ext in $extensions; do
            version=$(jq -r ".extensions.\"$ext\".version" conf/third_party_pg_extensions.json)
            url=$(jq -r ".extensions.\"$ext\".url" conf/third_party_pg_extensions.json)
            ./scripts/build_and_deploy_third_party_pg_extensions.sh "$ext,$version,$url"
          done

  publish-pgml:
    name: Publish pgml for PostgreSQL ${{ matrix.pg_version }} on ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    container:
      image: python:3.11-bookworm # Same distro as our Dockerfile, for compatibility
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            pg_version: 15
            arch: amd64
          - runner: buildjet-4vcpu-ubuntu-2204-arm
            pg_version: 15
            arch: arm64

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          repository: postgresml/postgresml
          ref: v2.7.10

      - name: Retrieve GitHub Tag Version
        id: version
        run: echo "version=2.7.10" >> $GITHUB_OUTPUT

      - name: Retrieve Arch
        id: arch
        run: |
          arch_val=$(uname -m)
          if [ "$arch_val" == "x86_64" ]; then
              mapped_arch="amd64"
          elif [ "$arch_val" == "aarch64" ]; then
              mapped_arch="arm64"
          else
              mapped_arch="$arch_val"
          fi
          echo "arch=$mapped_arch" >> $GITHUB_OUTPUT

      - name: Update Dependencies
        run: apt-get update && apt-get install -y --no-install-recommends sudo curl wget gnupg2 ca-certificates jq lsb-release cmake make

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update && sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}
          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/extension/ /usr/lib/postgresql/${{ matrix.pg_version }}/lib/
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Install pgrx
        run: cargo install cargo-pgrx --version 0.10.0

      - name: Initialize pgrx for Current PostgreSQL Version
        working-directory: pgml-extension/
        run: cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

      - name: Update pgml schema to paradedb
        working-directory: pgml-extension/
        run: |
          sed -i "s/\(schema = \).*/\1'paradedb'/" pgml.control
          find . -type f -exec sed -i 's/pgml\./paradedb\./g' {} +

      # Install build requirements for pgml
      - name: Install pgml Build Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
              checkinstall \
              bison \
              flex \
              libreadline-dev \
              libopenblas-dev

      - name: Package pgml Extension with pgrx
        working-directory: pgml-extension/
        run: |
          git config --global --add safe.directory /__w/paradedb/paradedb    
          git submodule update --init --recursive && RUSTFLAGS="-A warnings" cargo pgrx package

      - name: Create .deb Package
        working-directory: pgml-extension/
        run: |
          # Create installable package
          mkdir archive
          cp `find target/release -type f -name "pgml*"` archive
          package_dir=pgml-${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ matrix.arch }}-linux-gnu

          # Copy files into directory structure
          mkdir -p ${package_dir}/usr/lib/postgresql/lib
          mkdir -p ${package_dir}/var/lib/postgresql/extension
          cp archive/*.so ${package_dir}/usr/lib/postgresql/lib
          cp archive/*.control ${package_dir}/var/lib/postgresql/extension
          cp archive/*.sql ${package_dir}/var/lib/postgresql/extension

          # Symlinks to copy files into directory structure
          mkdir -p ${package_dir}/usr/lib/postgresql/${{ matrix.pg_version }}/lib
          mkdir -p ${package_dir}/usr/share/postgresql/${{ matrix.pg_version}}/extension
          cp archive/*.so ${package_dir}/usr/lib/postgresql/${{ matrix.pg_version }}/lib
          cp archive/*.control ${package_dir}/usr/share/postgresql/${{ matrix.pg_version }}/extension
          cp archive/*.sql ${package_dir}/usr/share/postgresql/${{ matrix.pg_version }}/extension

          # Create control file (package name cannot have underscore)
          mkdir -p ${package_dir}/DEBIAN
          touch ${package_dir}/DEBIAN/control
          deb_version=${{ steps.version.outputs.version }}
          CONTROL_FILE="${package_dir}/DEBIAN/control"
          echo 'Package: pgml' >> $CONTROL_FILE
          echo 'Version:' ${deb_version} >> $CONTROL_FILE
          echo 'Architecture: ${{ matrix.arch }}' >> $CONTROL_FILE
          echo 'Maintainer: PostgresML' >> $CONTROL_FILE
          echo 'Description: Generative AI and simple ML in PostgreSQL' >> $CONTROL_FILE

          # Create .deb package
          sudo chown -R root:root ${package_dir}
          sudo chmod -R 00755 ${package_dir}
          sudo dpkg-deb --build --root-owner-group ${package_dir}

      - name: Create GitHub Release for pgml
        uses: softprops/action-gh-release@v1
        with:
          repository: paradedb/third-party-pg_extensions
          tag_name: pgml-v${{ steps.version.outputs.version }}-${{ matrix.arch }}
          name: pgml ${{ steps.version.outputs.version }} ${{ matrix.arch }}
          body: Internal ParadeDB Release for pgml version ${{ steps.version.outputs.version }} for arch ${{ matrix.arch }}. This release is not intended for public use.
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}

      - name: Retrieve GitHub Release Upload URL
        id: upload_url
        run: echo UPLOAD_URL=$(curl --silent https://api.github.com/repos/paradedb/third-party-pg_extensions/releases/latest | jq .upload_url --raw-output) >> $GITHUB_OUTPUT

      - name: Upload pgml .deb to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
        with:
          upload_url: ${{ steps.upload_url.outputs.upload_url }}
          asset_path: ./pgml-extension/pgml-${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ matrix.arch }}-linux-gnu.deb
          asset_name: pgml-v${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ matrix.arch }}-linux-gnu.deb
          asset_content_type: application/vnd.DEBIAN.binary-package
