name: Bump version number

on:
  pull-request:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Bump version (dev only)
        if: github.ref == 'refs/heads/dev'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          poetry version patch
          VERSION=$(poetry version | awk '{print $2}')
          git commit -am "Bump version to $VERSION"
          git tag $VERSION
          git push --follow-tags
