name: Publish Python Package

on:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - dev


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Set Environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "::set-output name=environment::dev"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "::set-output name=environment::staging"
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "::set-output name=environment::prod"
          fi
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true


      - name: Retrieve Current Version Number
        run: |
          echo "The value of ENV_VARIABLE_NAME is: ${{ vars.VERSION_MINOR }}"






      # - name: Build and publish to PyPI
      #   env:
      #     ENVIRONMENT: ${{ steps.env.outputs.environment }}
      #   run: |
      #     poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      #     poetry build
      #     poetry publish
