# workflows/publish-auth0.yml
#
# Publish Auth0
# Publish our Auth0 tenant configuration to the Auth0 tenant.

name: Publish Auth0

on:
  push:
    branches:
      - main
      - staging
      - dev
  workflow_dispatch:

concurrency:
  group: publish-auth0-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-auth0:
    name: Publish Auth0 Tenant
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Set Environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
            echo "auth0_secret=${{ secrets.AUTH_CLIENT_SECRET_PROD }}" >> $GITHUB_OUTPUT
            echo "stripe_api_key=${{ secrets.STRIPE_API_KEY_PROD }}" >> $GITHUB_OUTPUT
            echo "intercom_access_token=${{ secrets.INTERCOM_ACCESS_TOKEN }}" >> $GITHUB_OUTPUT
            echo "Using prod configuration..."
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "Using staging configuration..."
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
            echo "auth0_secret=${{ secrets.AUTH_CLIENT_SECRET_DEV }}" >> $GITHUB_OUTPUT
            echo "stripe_api_key=${{ secrets.STRIPE_API_KEY_DEV }}" >> $GITHUB_OUTPUT
            echo "intercom_access_token=${{ secrets.INTERCOM_ACCESS_TOKEN }}" >> $GITHUB_OUTPUT
            echo "Using dev configuration..."
          fi

      - name: Install Dependencies
        working-directory: .github/workflows/helpers/auth0/
        run: yarn

      - name: Publish Auth0 Tenant
        working-directory: .github/workflows/helpers/auth0/
        env:
          AUTH0_CLIENT_SECRET: ${{ steps.env.outputs.auth0_secret }}
          GOOGLE_OAUTH_SECRET: ${{ secrets.GOOGLE_OAUTH_SECRET }}
          STRIPE_API_KEY: ${{ steps.env.outputs.stripe_api_key }}
          INTERCOM_ACCESS_TOKEN: ${{ steps.env.outputs.intercom_access_token }}
        run: yarn deploy:${{ steps.env.outputs.environment }}
