# workflows/publish-pg_bm25.yml
#
# pg_bm25: Publish
# Build and publish the pg_bm25 extension to PGXN (PostgreSQL Extension Network).

name: Publishing

on:
  push:
    branches:
      - phil/proper-packaging # TODO: remove this after testing
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: publish-pg_bm25-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-pg_bm25-to-pgxn:
    name: Publish pg_bm25 to PGXN
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    strategy:
      matrix:
        pg_version: [15]
    env:
      GITHUB_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
      PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
      PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
      PG_VERSION_MAJOR: 15

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
          key: ${{ runner.os }}-cargo-pgrx-0.9.8-grcov
          restore-keys: |
            ${{ runner.os }}-cargo-pgrx-0.9.8-grcov
            ${{ runner.os }}-cargo-pgrx
            ${{ runner.os }}-cargo

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update && sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}
          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/extension/ /usr/lib/postgresql/${{ matrix.pg_version }}/lib/
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Install pgrx
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo install cargo-pgrx --version 0.9.8

      - name: Initialize pgrx for Current PostgreSQL Version
        working-directory: pg_bm25/
        run: cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

      - name: Retrieve GitHub Tag Version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update Version
        working-directory: pg_bm25/
        # run: sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"${{ steps.version.outputs.version }}\"/" Cargo.toml
        run: sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"9.9.9\"/" Cargo.toml

      - name: Package pg_bm25 Extension with pgrx
        working-directory: pg_bm25/
        run: cargo pgrx package

      - name: Generate META.json File for PGXN
        run: |
          ./scripts/generate_pgxn_meta_file.sh pg_bm25/
          mv pg_bm25/META.json target/release/pg_bm25-pg${{ env.PG_VERSION_MAJOR }}/

      - name: Bundle the pg_bm25 Extension for PGXN
        working-directory: target/release/pg_bm25-pg${{ env.PG_VERSION_MAJOR }}/
        run: pgxn-bundle

      - name: Publish the pg_bm25 Extension
        working-directory: target/release/pg_bm25-pg${{ env.PG_VERSION_MAJOR }}/
        run: pgxn-release
