# workflows/publish-third-party-pg_extensions.yml
#
# Third-Party PostgreSQL Extensions: Publish
# Build and publish the third-party PostgreSQL extensions used by ParadeDB to
# GitHub Releases. We use a separate storage repo, paradedb/third-party-extensions)
# for clarity and to avoid bloating the ParadeDB repo with binaries.

name: Publishing

on:
  push:
    branches:
      - phil/apt # TODO: remove this after testing
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: publish-third-party-pg_extensions-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-third-party-pg_extensions:
    name: Publish Third Party PostgreSQL Extensions for PostgreSQL ${{ matrix.pg_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [11, 12, 13, 14, 15]

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
          key: ${{ runner.os }}-cargo-pgrx-0.9.8
          restore-keys: |
            ${{ runner.os }}-cargo-pgrx
            ${{ runner.os }}-cargo

      - name: Retrieve GitHub Tag Version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Retrieve Arch
        id: arch
        run: |
          arch_val=$(uname -m)
          if [ "$arch_val" == "x86_64" ]; then
              mapped_arch="amd64"
          elif [ "$arch_val" == "aarch64" ]; then
              mapped_arch="arm64"
          else
              mapped_arch="$arch_val"
          fi
          echo "arch=$mapped_arch" >> $GITHUB_OUTPUT

      - name: Install pgrx
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo install cargo-pgrx --version 0.9.8

      - name: Initialize pgrx for Current PostgreSQL Version
        working-directory: pg_search/
        run: cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

      #
      - name: Build and Push each third-party extension to the storage repo
        env:
          PGML_VERSION: 2.7.8
          PGVECTOR_VERSION: 0.5.0
          PGAUDIT_VERSION: 1.7.0
          PG_NET_VERSION: 0.7.2
          PG_GRAPHQL_VERSION: 1.3.0
          PG_JSONSCHEMA_VERSION: 0.1.4
          PGNODEMX_VERSION: 1.6
          PG_CRON_VERSION: 1.6.0
          PG_IVM_VERSION: 1.5.1
          PG_HASHIDS_VERSION: 1.2.1
          PG_REPACK_VERSION=: ver_1.4.8
          PG_STAT_MONITOR_VERSION: 2.0.1
          PG_HINT_PLAN_VERSION: REL15_1_5_0
          PG_ROARINGBITMAP_VERSION: 0.5.4
          PGFACETING_VERSION: 0.1.0
          PGTAP_VERSION: 1.3.0
          POSTGIS_VERSION: 3.4.0
          PGROUTING_VERSION: 3.5.0
          PGSQL_HTTP_VERSION: 1.6.0
          HYPOPG_VERSION: 1.4.0
          RUM_VERSION: 1.3.13
          AGE_VERSION: 1.4.0-rc0
        run: |



          # For each extension listed here, build and package in the script!

      - name: Retrieve GitHub Release Upload URL
        id: upload_url
        run: echo UPLOAD_URL=$(curl --silent https://api.github.com/repos/${{ github.repository }}/releases/latest | jq .upload_url --raw-output) >> $GITHUB_OUTPUT

      - name: Upload pg_bm25 .deb to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
        with:
          upload_url: ${{ steps.upload_url.outputs.upload_url }}
          asset_path: ./pg_bm25-${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ steps.arch.outputs.arch }}-linux-gnu.deb
          asset_name: pg_bm25-${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ steps.arch.outputs.arch }}-linux-gnu.deb
          asset_content_type: application/vnd.DEBIAN.binary-package
