# workflows/publish-pg_sparse.yml
#
# Publish pg_sparse
# Build and publish the pg_sparse extension as a .deb to GitHub Releases.

name: Publish pg_sparse

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "The version to set for the pg_sparse release. This publishes the latest commit of the chosen branch and uploads it to the pre-existing GitHub Release of the provided version."
        required: true
        default: ""

concurrency:
  group: publish-pg_sparse-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-pg_sparse:
    name: Publish pg_sparse for PostgreSQL ${{ matrix.pg_version }} on ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            pg_version: 16
            arch: amd64
          - runner: ubicloud-standard-2-ubuntu-2204-arm
            pg_version: 16
            arch: arm64

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Retrieve Ubuntu & GitHub Tag Versions
        id: version
        run: |
          # If no workflow_dispatch version is provided, we use workflow tag trigger version
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi
          echo "ubuntu_version=$(lsb_release -rs | sed 's/\.//')" >> $GITHUB_OUTPUT

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
          sudo apt-get update && sudo apt-get install -y --no-install-recommends postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}

          # Update permissions for PostgreSQL directories for extensions installation
          sudo chown -R $(whoami) \
            /usr/share/postgresql/${{ matrix.pg_version }}/extension/ \
            /usr/lib/postgresql/${{ matrix.pg_version }}/bin/ \
            /usr/lib/postgresql/${{ matrix.pg_version }}/lib/ \
            /usr/include/postgresql/${{ matrix.pg_version }}/server/ \
            /usr/share/postgresql/${{ matrix.pg_version }}/contrib/ \
            /usr/local/share/man/ \
            /usr/share/doc/

          # Add PostgreSQL binaries to PATH
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Build & Package pg_sparse as a .deb
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
          PG_MAJOR_VERSION: ${{ matrix.pg_version }}
          ARCH: ${{ matrix.arch }}
        run: |
          # Download & extract source code
          mkdir -p "/tmp/pg_sparse-${{ steps.version.outputs.version }}"
          cp -r pg_sparse/** "/tmp/pg_sparse-${{ steps.version.outputs.version }}/"
          cd "/tmp/pg_sparse-${{ steps.version.outputs.version }}"

          # Set pg_config path
          export PG_CONFIG=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

          # Set OPTFLAGS to an empty string if it's not already set
          OPTFLAGS=${OPTFLAGS:-""}

          # Disable -march=native to avoid "illegal instruction" errors on macOS arm64 by
          # setting OPTFLAGS to an empty string
          OPTFLAGS=""

          # Build pg_sparse
          make USE_PGXS=1 OPTFLAGS="$OPTFLAGS" "-j$(nproc)"

          # Create a temporary directory for packaging
          PKGDIR=/tmp/pg_sparse_pkg
          mkdir -p "$PKGDIR"

          # Install the built files to the package directory
          make USE_PGXS=1 DESTDIR="$PKGDIR" install

          # Create DEBIAN control directory
          mkdir -p "$PKGDIR/DEBIAN"

          # Create a control file with package information
          cat <<EOF >"$PKGDIR/DEBIAN/control"
          Package: pg-sparse
          Version: ${{ steps.version.outputs.version }}
          Section: database
          Priority: optional
          Architecture: ${{ matrix.arch }}
          Depends: postgresql-${{ matrix.pg_version }}
          Maintainer: ParadeDB <support@paradedb.com>
          Description: pg_sparse: Sparse vector data type and sparse HNSW access methods
          EOF

          # Build the package
          dpkg-deb --build "$PKGDIR" "/tmp/pg_sparse_${{ steps.version.outputs.version }}-1_${{ matrix.arch }}.deb"

      # We retrieve the GitHub release for the specific release version
      - name: Retrieve GitHub Release Upload URL
        id: upload_url
        run: echo UPLOAD_URL=$(curl --silent https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.version.outputs.version }} | jq .upload_url --raw-output | sed "s/{?name,label}//") >> $GITHUB_OUTPUT

      - name: Upload pg_sparse .deb to GitHub Release
        run: |
          curl -X POST "${{ steps.upload_url.outputs.upload_url }}?name=pg_sparse-v${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ matrix.arch }}-ubuntu${{ steps.version.outputs.ubuntu_version }}.deb" \
          -H "Authorization: token ${{ secrets.GHA_CREATE_RELEASE_PAT }}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary "@/tmp/pg-sparse_${{ steps.version.outputs.version }}-1_${{ matrix.arch }}.deb"
