# workflows/publish-pg_lakehouse.yml
#
# Publish pg_lakehouse
# Build and publish the pg_lakehouse extension as a .deb to GitHub Releases.

name: Publish pg_lakehouse

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "The version to set for the pg_lakehouse release. This publishes the latest commit of the chosen branch and uploads it to the pre-existing GitHub Release of the provided version."
        required: true
        default: ""

concurrency:
  group: publish-pg_lakehouse-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-pg_lakehouse:
    name: Publish pg_lakehouse for PostgreSQL ${{ matrix.pg_version }} on ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    container:
      image: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          # Ubuntu 22.04
          - runner: depot-ubuntu-22.04-4
            image: ubuntu:22.04
            pg_version: 14
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: ubuntu:22.04
            pg_version: 14
            arch: arm64
          - runner: depot-ubuntu-22.04-4
            image: ubuntu:22.04
            pg_version: 15
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: ubuntu:22.04
            pg_version: 15
            arch: arm64
          - runner: depot-ubuntu-22.04-4
            image: ubuntu:22.04
            pg_version: 16
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: ubuntu:22.04
            pg_version: 16
            arch: arm64
          # Debian 11
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:11-slim
            pg_version: 14
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:11-slim
            pg_version: 14
            arch: arm64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:11-slim
            pg_version: 15
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:11-slim
            pg_version: 15
            arch: arm64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:11-slim
            pg_version: 16
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:11-slim
            pg_version: 16
            arch: arm64
          # Debian 12
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:12-slim
            pg_version: 14
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:12-slim
            pg_version: 14
            arch: arm64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:12-slim
            pg_version: 15
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:12-slim
            pg_version: 15
            arch: arm64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:12-slim
            pg_version: 16
            arch: amd64
          - runner: depot-ubuntu-22.04-arm-4
            image: debian:12-slim
            pg_version: 16
            arch: arm64
          # TODO: Add Ubuntu 20.04, RedHat UBI 8, and RedHat UBI 9
          # TODO: Maybe consider removing debian-slim for regular debian, and removing manual apt downloads

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Install Debian Dependencies
        if: ${{ matrix.image }} == 'debian:11-slim' || ${{ matrix.image }} == 'debian:12-slim'
        run: apt-get update && apt-get install -y sudo wget curl gnupg lsb-release pkg-config libssl-dev jq

      # Note: DataFusion requires Rust nightly to enable packed_simd for SIMD optimizations. We
      # fix Rust nightly because current latest (1.80.0) is causing compilation issues with some dependencies
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-04-21

      - name: Retrieve OS & GitHub Tag Versions
        id: version
        run: |
          # If no workflow_dispatch version is provided, we use workflow tag trigger version
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi
          # Retrieve the OS Distributor ID (-is) and Release (-rs) Versions
          DISTRO=$(echo "$(lsb_release -is)" | tr '[:upper:]' '[:lower:]')
          RELEASE=$(lsb_release -rs)
          echo "OS Version: $DISTRO-$RELEASE"
          echo "os_version=$DISTRO-$RELEASE" >> $GITHUB_OUTPUT

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update && sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }} debhelper devscripts dput gnupg
          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/ /usr/lib/postgresql/${{ matrix.pg_version }}/ /var/lib/postgresql/${{ matrix.pg_version }}/
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Install pgrx
        run: cargo install -j $(nproc) --locked cargo-pgrx --version 0.11.3

      - name: Initialize pgrx for Current PostgreSQL Version
        working-directory: pg_lakehouse/
        run: cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

      # TODO: Add telemetry to pg_lakehouse
      - name: Package pg_lakehouse Extension with pgrx
        working-directory: pg_lakehouse/
        run: cargo pgrx package --features telemetry

      - name: Create .deb Package
        run: |
          # Create installable package
          mkdir archive
          cp `find target/release -type f -name "pg_lakehouse*"` archive
          package_dir=pg_lakehouse-${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ matrix.arch }}-${{ steps.version.outputs.os_version }}

          # Copy files into directory structure
          mkdir -p ${package_dir}/usr/lib/postgresql/lib
          mkdir -p ${package_dir}/var/lib/postgresql/extension
          cp archive/*.so ${package_dir}/usr/lib/postgresql/lib
          cp archive/*.control ${package_dir}/var/lib/postgresql/extension
          cp archive/*.sql ${package_dir}/var/lib/postgresql/extension

          # Symlinks to copy files into directory structure
          mkdir -p ${package_dir}/usr/lib/postgresql/${{ matrix.pg_version }}/lib
          mkdir -p ${package_dir}/usr/share/postgresql/${{ matrix.pg_version}}/extension
          cp archive/*.so ${package_dir}/usr/lib/postgresql/${{ matrix.pg_version }}/lib
          cp archive/*.control ${package_dir}/usr/share/postgresql/${{ matrix.pg_version }}/extension
          cp archive/*.sql ${package_dir}/usr/share/postgresql/${{ matrix.pg_version }}/extension

          # Create control file (package name cannot have underscore)
          mkdir -p ${package_dir}/DEBIAN
          touch ${package_dir}/DEBIAN/control
          deb_version=${{ steps.version.outputs.version }}
          CONTROL_FILE="${package_dir}/DEBIAN/control"
          echo 'Package: pg-lakehouse' >> $CONTROL_FILE
          echo 'Version:' ${deb_version} >> $CONTROL_FILE
          echo 'Section: database' >> $CONTROL_FILE
          echo 'Priority: optional' >> $CONTROL_FILE
          echo 'Architecture: ${{ matrix.arch }}' >> $CONTROL_FILE
          echo 'Depends: postgresql-${{ matrix.pg_version }}' >> $CONTROL_FILE
          echo 'Maintainer: ParadeDB <support@paradedb.com>' >> $CONTROL_FILE
          echo 'Description: An analytical query engine for Postgres' >> $CONTROL_FILE

          # Create .deb package
          # Note: We specify `xz` compression for compatibility with Debian 11
          sudo chown -R root:root ${package_dir}
          sudo chmod -R 00755 ${package_dir}
          sudo dpkg-deb -Zxz --build --root-owner-group ${package_dir}

      # We retrieve the GitHub release for the specific release version
      - name: Retrieve GitHub Release Upload URL
        id: upload_url
        run: echo UPLOAD_URL=$(curl --silent https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.version.outputs.version }} | jq .upload_url --raw-output) >> $GITHUB_OUTPUT

      - name: Upload pg_lakehouse .deb to GitHub Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GHA_CREATE_RELEASE_PAT }}
          upload_url: ${{ steps.upload_url.outputs.upload_url }}
          asset_path: ./pg_lakehouse-${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ matrix.arch }}-${{ steps.version.outputs.os_version }}.deb
          asset_name: pg_lakehouse-v${{ steps.version.outputs.version }}-pg${{ matrix.pg_version }}-${{ matrix.arch }}-${{ steps.version.outputs.os_version }}.deb
