# workflows/run-tests.yml
#
# Run Tests
# Run unit and integration tests.

name: "Run Tests"

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "core/**"
      - "retake/**"
  workflow_dispatch:

# This guarantees that if you push many commits to the same PR, only the latest
# commit will get run (others get cancelled)
concurrency:
  group: run-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v3

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          poetry install

      # Tech Debt: Disable sentence_transformer test in GH actions
      # due to CUDA issue in GH runner
      - name: Run Pytest
        run: |
          poetry run pytest --ignore=core/transform/tests/test_sentence_transformers.py
