# workflows/test-docs.yml
#
# Test Docs
# Test our documentation for broken links via Mintlify.

name: Test Docs

on:
  pull_request:
    branches:
      - main
      - staging
      - dev
    paths:
      - "docs/**"
      - ".github/workflows/test-docs.yml"
  workflow_dispatch:

concurrency:
  group: test-docs-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-docs:
    name: Test Docs for Broken Links
    runs-on: depot-ubuntu-22.04-4

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Install Mintlify CLI
        run: npm install -g mintlify

      - name: Test Docs for Broken Links
        working-directory: docs/
        run: |
          output=$(mintlify broken-links)

          # Check if the output contains any broken links
          if [[ "$output" == *"No broken links found."* ]]; then
            echo "No broken links found."
          else
            >&2 echo "$output"
            exit 1
          fi
