# workflows/test-pg_bm25.yml
#
# pg_bm25: Tests
# Run unit and packaging tests for the pg_bm25 extension.

name: Testing

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "pg_bm25/**"
      - ".github/workflows/test-pg_bm25.yml"
      - "!pg_bm25/README.md"
  workflow_dispatch:

concurrency:
  group: test-pg_bm25-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-pg_bm25:
    name: Test pg_bm25 on PostgreSQL ${{ matrix.pg_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [11, 12, 13, 14, 15]

    steps:
      - name: Sparse Checkout Git Repository
        uses: actions/checkout@v4

      # Attempt to download the Rust binaries artifact
      - name: Download Rust binaries artifact
        uses: actions/download-artifact@v2
        with:
          name: rust-binaries
          path: ~/.cargo/bin/
        continue-on-error: true  # Don't fail the workflow if the artifact isn't found

      # - name: Cache Cargo Dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/registry
      #       ~/.cargo/git
      #       ~/.cargo/bin/
      #       ~/.rustup/
      #       pg_bm25/target
      #     key: ${{ runner.os }}-cargo-${{ hashFiles('pg_bm25/Cargo.lock') }}xw

      - name: Install Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update && sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}

      - name: Configure PostgreSQL Directories
        run: |
          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/extension/ /usr/lib/postgresql/${{ matrix.pg_version }}/lib/
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Install pgrx, grcov & llvm-tools-preview
        working-directory: pg_bm25
        run: |
          if ! command -v cargo-pgrx &> /dev/null; then
            cargo install cargo-pgrx --version 0.9.8
          fi
          if ! command -v grcov &> /dev/null; then
            cargo install grcov
          fi
          if ! rustup component list | grep -q 'llvm-tools-preview.*(installed)'; then
            rustup component add llvm-tools-preview
          fi

      - name: Upload Rust binaries as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rust-binaries
          path: ~/.cargo/bin/

      - name: Initialize pgrx for Current PostgreSQL Version
        working-directory: pg_bm25
        run: cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

      - name: Run pg_bm25 Unit Tests
        working-directory: pg_bm25
        run: |
          mkdir -p target/coverage target/coverage-report
          export LLVM_PROFILE_FILE="target/coverage/pg_bm25-%p-%m.profraw"
          export RUST_BACKTRACE=1
          cargo pgrx test

      - name: Generate Code Coverage Report
        working-directory: pg_bm25
        run: grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/coverage-report/

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./pg_bm25/target/coverage-report/
          files: lcov
          fail_ci_if_error: true

      - name: Run pg_bm25 Integration Tests
        working-directory: pg_bm25
        run: ./test/runtests.sh "${{ matrix.pg_version }}"
