# workflows/test-pg_search-stressgres.yml
#
# Test pg_search Stressgres
# Run the Stressgres stress testing against pg_search.

name: Test pg_search Stressgres

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - dev
      - main
    paths:
      - ".github/workflows/test-pg_search-stressgres.yml"
      - "pg_search/**"
      - "tokenizers/**"
  schedule:
    - cron: "1 0 * * 1,2,3,4,5" # Weekdays at 00:01 UTC
  push:
    branches:
      - dev
      - main
    paths:
      - "**/*.rs"
      - "**/*.toml"
  workflow_dispatch: {}

jobs:
  test-pg_search-stressgres:
    name: Run Stressgres on pg_search with PostgreSQL ${{ matrix.pg_version }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubicloud-standard-8
            pg_version: 17
            arch: amd64
    env:
      default_pg_version: 17

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          path: paradedb

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Extract pgrx Version
        id: pgrx
        working-directory: paradedb/pg_search/
        run: |
          version=$(cargo tree --depth 1 -i pgrx -p pg_search | head -n 1 | sed -E 's/.*v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Install Rust Cache
        uses: ubicloud/rust-cache@v2
        with:
          prefix-key: "v1-rust"
          key: ${{ matrix.pg_version }}-${{ steps.pgrx.outputs.version }}
          cache-targets: true
          cache-all-crates: true
          save-if: ${{ github.ref == 'refs/heads/dev' }}

      - name: Install required system tools
        run: sudo apt-get update && sudo apt-get install -y lsof

      - name: Install llvm-tools-preview
        run: rustup component add llvm-tools-preview

      - name: Install cargo-pgrx
        run: cargo install -j $(nproc) --locked cargo-pgrx --version ${{ steps.pgrx.outputs.version }} --debug

      - name: Download Asciinema v3.0.0-rc.3
        run: |
          curl -L https://github.com/asciinema/asciinema/releases/download/v3.0.0-rc.3/asciinema-x86_64-unknown-linux-gnu -o asciinema
          chmod +x asciinema
          mv asciinema /usr/local/bin/

      - name: Initialize cargo-pgrx environment
        run: cargo pgrx init "--pg${{ matrix.pg_version }}=download"

      - name: Checkout Stressgres Repo
        uses: actions/checkout@v4
        with:
          repository: paradedb/stressgres
          path: stressgres
          ref: neil/unpaused
          token: ${{ secrets.GHA_CREATE_RELEASE_PAT }}

      - name: Add pg_search to shared_preload_libraries
        working-directory: /home/runner/.pgrx/data-${{ matrix.pg_version }}/
        run: sed -i "s/^#shared_preload_libraries = .*/shared_preload_libraries = 'pg_search'/" postgresql.conf

      - name: Compile & install pg_search extension
        working-directory: paradedb/pg_search/
        run: cargo pgrx install --pg-config ~/.pgrx/${{ matrix.pg_version }}.*/pgrx-install/bin/pg_config --features=pg${{ matrix.pg_version }},icu

      - name: Start Postgres and create database
        working-directory: paradedb/tests/
        run: |
          RUST_BACKTRACE=1 cargo pgrx start pg${{ matrix.pg_version }}
          ~/.pgrx/${{ matrix.pg_version }}.*/pgrx-install/bin/createdb -p 288${{ matrix.pg_version }} -h localhost pg_search

      - name: Run Stressgres with Timeout
        working-directory: stressgres/
        # Must run cargo build before recording, or the build time will take up much of our recording before the timeout.
        # Asciinema must run in --headless for Github Actions, which is only available in 3.0.
        # Timeout will always exit with 124, which we should catch or the action step will fail.
        run: |
          RUST_BACKTRACE=1 cargo build && timeout 10m /usr/local/bin/asciinema rec \
            --headless \
            --command 'cargo run suites/ci.toml "host=localhost port=28817 dbname=postgres" false' \
            stressgres.cast || EXIT_CODE=$?

          if [ "$EXIT_CODE" -eq 124 ]; then
            echo "Process timed out as expected."
          fi

      - name: Create HTML from Template using sed file read
        shell: bash
        working-directory: stressgres/
        run: |
          TEMPLATE_PATH="$GITHUB_WORKSPACE/paradedb/.github/templates/stressgres.html"
          # Write the base64 encoded content to a temporary file
          base64 -w 0 stressgres.cast > temp_b64.txt
          
          # Use sed to replace the placeholder by:
          # 1. Removing the placeholder text on the matching line
          # 2. Inserting the contents of the temporary file
          sed '/{{BASE64_CONTENT}}/ {
            s/{{BASE64_CONTENT}}//
            r temp_b64.txt
          }' "$TEMPLATE_PATH" > stressgres.html

      - name: Upload stressgres.html
        uses: actions/upload-artifact@v4
        with:
          name: stressgres-session
          path: stressgres/stressgres.html

      - name: Print Postgres Logs
        run: cat ~/.pgrx/${{ matrix.pg_version }}.log

      - name: Notify Slack on Failure
        if: failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Stressgres pg_search Workflow failed in `paradedb/paradedb` -- investigate immediately!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
