# workflows/test-pg_bm25.yml
#
# pg_bm25: Tests
# Run unit and packaging tests for the pg_bm25 extension.

name: Testing

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "pg_bm25/**"
      - "!pg_bm25/README.md"
      - ".github/workflows/test-pg_bm25.yml"
  workflow_dispatch:

concurrency:
  group: test-pg_bm25-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-pg_bm25:
    name: Test pg_bm25 on PostgreSQL ${{ matrix.pg_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [11, 12, 13, 14, 15]

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Cache pgrx Initialization
        uses: actions/cache@v3
        id: cache-pgrx
        with:
          path: ~/.pgrx/
          key: pgrx-${{ runner.os }}-pg${{ matrix.pg_version }}




      - name: Install & Configure Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update
          sudo apt-get install -y postgresql-${{ matrix.pg_version }}
          sudo apt-get install -y postgresql-server-dev-${{ matrix.pg_version }}
          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/extension/ /usr/lib/postgresql/${{ matrix.pg_version }}/lib/
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Install pgrx, grcov & llvm-tools-preview
        working-directory: pg_bm25
        run: |
          cargo install cargo-pgrx --version 0.9.8
          cargo install grcov
          rustup component add llvm-tools-preview

       # Only run if cache miss
      - name: Initialize pgrx for Current PostgreSQL Version
        if: steps.cache-pgrx.outputs.cache-hit != 'true'
        working-directory: pg_bm25
        run: cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

      - name: Run pg_bm25 Integration Tests
        working-directory: pg_bm25
        run: ./test/runtests.sh "${{ matrix.pg_version }}"

      - name: Run pg_bm25 Unit Tests
        working-directory: pg_bm25
        run: |
          mkdir -p target/coverage target/coverage-report
          export LLVM_PROFILE_FILE="target/coverage/pg_bm25-%p-%m.profraw"
          export RUST_BACKTRACE=1
          cargo pgrx test --pg${{ matrix.pg_version }}

      - name: Generate Code Coverage Reports
        working-directory: pg_bm25
        run: grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing -o ./target/coverage-report/

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./pg_bm25/target/coverage-report/
          files: lcov
          fail_ci_if_error: true
