# workflows/test-paradedb.yml
#
# Testing: ParadeDB
# Lint Dockerfiles using Hadolint.

name: Testing

on:
  pull_request:
    branches:
      - main
      - staging
      - dev
    paths:
      - "docker/Dockerfile"
      - ".github/workflows/test-paradedb.yml"
  workflow_dispatch:

concurrency:
  group: test-paradedb-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-pg_search:
    name: Test ParadeDB on PostgreSQL ${{ matrix.pg_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [15]

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      # By using the docker-compose.dev.yml file, we also test that the build arguments are correct
      - name: Test Building ParadeDB Docker Image
        working-directory: docker/
        run: docker buildx create --use && docker compose -f docker-compose.dev.yml build
