# workflows/test-pg_sparse.yml
#
# Test pg_sparse
# Run unit and packaging tests for the pg_sparse extension.

name: Test pg_sparse

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
    paths:
      - "pg_sparse/**"
      - "!pg_sparse/README.md"
      - ".github/workflows/test-pg_sparse.yml"
  workflow_dispatch:

concurrency:
  group: test-pg_sparse-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-pg_sparse:
    name: Test pg_sparse on PostgreSQL ${{ matrix.pg_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg_version: [12, 13, 14, 15, 16]

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Remove old postgres, llvm, clang, and install appropriate version
        run: |
          sudo apt remove -y '^postgres.*' '^libpq.*' '^mono-llvm.*'
          apt list --installed 'clang*' 'llvm*' 'libclang*' 'libllvm*' | awk -F/ -e '{print $1}' | grep -P '\d' | grep -vP '\D15(\D.*)?$' | xargs sudo apt remove -y
          sudo apt-get install -y llvm-15-dev libclang-15-dev clang-15 gcc

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update && sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}
          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/extension/ /usr/lib/postgresql/${{ matrix.pg_version }}/lib/
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Install pgrx, grcov & llvm-tools-preview
        run: |
          cargo install cargo-pgrx --version 0.11.0 && cargo install grcov
          rustup component add llvm-tools-preview

      - name: Initialize pgrx for Current PostgreSQL Version
        working-directory: pg_sparse/
        run: cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config

      - name: Run pg_sparse Integration Tests
        working-directory: pg_sparse/
        run: ./test/runtests.sh -p sequential -v "${{ matrix.pg_version }}"

      - name: Run pg_sparse Unit Tests
        env:
          LLVM_PROFILE_FILE: target/coverage/pg_sparse-%p-%m.profraw
          RUST_BACKTRACE: 1
        run: |
          mkdir -p target/coverage target/coverage-report
          cd pg_sparse/ && cargo pgrx test --features pg${{ matrix.pg_version }}
